"""adding date and month_dir colums

Revision ID: 00a3988ffab1
Revises: 11bb97ea7892
Create Date: 2026-04-28 20:20:39.739925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a3988ffab1'
down_revision: Union[str, Sequence[str], None] = '11bb97ea7892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_table', sa.Column('date_creation', sa.DateTime(), nullable=False))
    op.add_column('main_table', sa.Column('month_dir', sa.VARCHAR(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_table', 'month_dir')
    op.drop_column('main_table', 'date_creation')
    # ### end Alembic commands ###
