"""add unique to file_path

Revision ID: 11bb97ea7892
Revises: 305ea8e4ec8e
Create Date: 2026-04-22 23:17:52.817656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11bb97ea7892'
down_revision: Union[str, Sequence[str], None] = '305ea8e4ec8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'main_table', ['file_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'main_table', type_='unique')
    # ### end Alembic commands ###
