"""move PK to file_id its

Revision ID: 305ea8e4ec8e
Revises: 708347f6c9d9
Create Date: 2026-04-22 22:55:00.242594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305ea8e4ec8e'
down_revision: Union[str, Sequence[str], None] = '708347f6c9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('file_id'), table_name='main_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('file_id'), 'main_table', ['file_id'], unique=True)
    # ### end Alembic commands ###
