"""tele_file_id column

Revision ID: 708347f6c9d9
Revises: f11069927730
Create Date: 2026-04-20 14:15:58.831115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708347f6c9d9'
down_revision: Union[str, Sequence[str], None] = 'f11069927730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_table', sa.Column('tele_file_id', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_table', 'tele_file_id')
    # ### end Alembic commands ###
