"""add new column 'file_size'

Revision ID: 74d5734aeac7
Revises: ff38bb056ac4
Create Date: 2026-05-20 16:26:02.948225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d5734aeac7'
down_revision: Union[str, Sequence[str], None] = 'ff38bb056ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_table', sa.Column('file_size', sa.BIGINT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_table', 'file_size')
    # ### end Alembic commands ###
