"""init

Revision ID: 7e64ce7f27e1
Revises: 
Create Date: 2026-04-19 20:31:22.041747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e64ce7f27e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_table',
    sa.Column('user_id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_table')
    # ### end Alembic commands ###
