"""add media_group columns

Revision ID: 7f23d8c17e99
Revises: d3cd6e1c7cc6
Create Date: 2026-05-30 21:01:05.458243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f23d8c17e99'
down_revision: Union[str, Sequence[str], None] = 'd3cd6e1c7cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_table', sa.Column('media_group_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('main_table', sa.Column('media_group_name', sa.VARCHAR(length=125), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_table', 'media_group_name')
    op.drop_column('main_table', 'media_group_id')
    # ### end Alembic commands ###
