"""created file_name column

Revision ID: 8d74d329c9f5
Revises: 9381061fddc9
Create Date: 2026-04-28 22:00:26.942906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d74d329c9f5'
down_revision: Union[str, Sequence[str], None] = '9381061fddc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_table', sa.Column('file_name', sa.VARCHAR(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_table', 'file_name')
    # ### end Alembic commands ###
