"""added autoincreasment to file_id

Revision ID: 9381061fddc9
Revises: 00a3988ffab1
Create Date: 2026-04-28 21:54:21.937033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9381061fddc9'
down_revision: Union[str, Sequence[str], None] = '00a3988ffab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('main_table', 'file_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('main_table', 'file_id',
               existing_type=sa.BIGINT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
