"""added 'date_dir' column

Revision ID: c85ba8a60632
Revises: da6b0677e810
Create Date: 2026-05-12 19:42:37.990888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85ba8a60632'
down_revision: Union[str, Sequence[str], None] = 'da6b0677e810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_table', sa.Column('date_dir', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_table', 'date_dir')
    # ### end Alembic commands ###
