"""empty message

Revision ID: d3cd6e1c7cc6
Revises: 74d5734aeac7
Create Date: 2026-05-24 20:23:36.168737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cd6e1c7cc6'
down_revision: Union[str, Sequence[str], None] = '74d5734aeac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_table', sa.Column('file_type', sa.VARCHAR(length=100), nullable=False, server_default='document'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_table', 'file_type')
    # ### end Alembic commands ###
