"""str instead of int in file_id

Revision ID: f11069927730
Revises: 7e64ce7f27e1
Create Date: 2026-04-19 20:33:00.251860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f11069927730'
down_revision: Union[str, Sequence[str], None] = '7e64ce7f27e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('main_table', 'file_id',
               existing_type=mysql.INTEGER(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('main_table', 'file_id',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
