"""add user_quota table

Revision ID: ff38bb056ac4
Revises: c85ba8a60632
Create Date: 2026-05-20 15:49:22.605181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff38bb056ac4'
down_revision: Union[str, Sequence[str], None] = 'c85ba8a60632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_quota',
    sa.Column('user_id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('used_space', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quota')
    # ### end Alembic commands ###
